version: "3"
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
        - $PWD/database/:/data/db
  srv:
    build: .
    volumes:
      - $PWD:/user/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
